name: Feature Request
description: Propose a new feature
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the feature
    validations:
      required: true
